name: Label New Issues as "To Do"

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Label new issue as "To Do"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "To Do"